default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: vagrant
  password: vagrant

development:
  <<: *default
  database: musicians_development

test:
  <<: *default
  database: musicians_test

production:
  <<: *default
  database: musicians_production
  username: musicians
  password: <%= ENV['MUSICIANS_DATABASE_PASSWORD'] %>
