# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7ba370f65178b661fbef17bd7af4500a686be6dc49fe2321699dc786e73484bc22f40b01704a5fcaea27204218b777723df4ed32ba30c06dfd7a95d932ea5d2

test:
  secret_key_base: d6203f9948cf9137811350262b0aa48dfb72123d729fc7cf16a3f4fd4291872dff9c7aa39cd37766c32ea7046a0916b7569a1ad6b66a54ab14f24ecb630e5af7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
